name: Build and upload wheels
on: workflow_dispatch:
jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          CIBW_BUILD: cp39-* cp310-* cp311-* cp312-*
          CIBW_BEFORE_BUILD: "pip install maturin"
          CIBW_BUILD_FRONTEND: "build"
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.9"
        with:
          package-dir: bindings/python
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl