name: Build and upload wheels
on: workflow_dispatch

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install protoc (macOS)
        if: runner.os == 'macOS'
        run: brew install protobuf

      - name: Install protoc (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_BEFORE_BUILD: pip install maturin
          CIBW_BUILD_FRONTEND: build
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.9"

          CIBW_BEFORE_BUILD_LINUX: >
            yum install -y unzip &&
            curl -Lfo /tmp/pb.zip
            https://github.com/protocolbuffers/protobuf/releases/download/v24.5/protoc-24.5-linux-x86_64.zip &&
            unzip -q -o /tmp/pb.zip -d /usr/local &&
            protoc --version &&
            export PROTOC=/usr/local/bin/protoc &&
            echo "export PROTOC=/usr/local/bin/protoc" >> $HOME/.bashrc
          CIBW_ENVIRONMENT_LINUX: "PROTOC=/usr/local/bin/protoc"

        with:
          package-dir: bindings/python

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl